# Generated by Django 4.0.6 on 2022-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, default='/foods/default.jpg', null=True, upload_to='foods')),
            ],
        ),
    ]
