# Generated by Django 4.0.6 on 2022-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
