# Generated by Django 4.0.6 on 2022-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_alter_food_price_alter_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
